config/routes.rb
Rails.application.routes.draw do

  get "profile", to: "pages#settings"
  get "stat", to: 'pages#statistics'
  get "settings/reload", to: "pages#reload"
  get "get_sites", to: "pages#get_sites"
  get "get_deadline", to: "pages#get_deadline"
  #get "settings/new_db", to: "pages#new_db"
  resources :cmd, only: [:new, :create]

  resources :tickets, param: :number do
    member do
      post 'create_message'
    end
  end
  resources :role_permissions
  get 'reports/create'
  resources :reports,  only: [:new]
  resources :roles, controller: :p_roles

  get 'photo_reports/create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :jobs
  resources :prices
  resources :accounts do
    resource :password, only: [:new, :update] do
      member do
        get :switch
      end
    end
    resource :roles, controller: 'ars' , only: [:create, :destroy]
  end
  resources :brigades
  resources :ticket_types
  resources :statuses
  resources :photos, controller: 'images'
  resources :documents
  resources :ticket_descriptions
  resources :sites do
    resources :photos
  end

  root to: 'tickets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ticket_description.rb
class TicketDescription < ApplicationRecord
  has_many :tickets
end

app/controllers/ticket_descriptions_controller.rb
class TicketDescriptionsController < ApplicationController
  before_action :set_ticket_description, only: [:show, :edit, :update, :destroy]

  # GET /ticket_descriptions
  # GET /ticket_descriptions.json
  def index
    @ticket_descriptions = TicketDescription.all
  end

  # GET /ticket_descriptions/1
  # GET /ticket_descriptions/1.json
  def show
  end

  # GET /ticket_descriptions/new
  def new
    @ticket_description = TicketDescription.new
  end

  # GET /ticket_descriptions/1/edit
  def edit
  end

  # POST /ticket_descriptions
  # POST /ticket_descriptions.json
  def create
    @ticket_description = TicketDescription.new(ticket_description_params)

    respond_to do |format|
      if @ticket_description.save
        format.html { redirect_to @ticket_description, notice: 'Ticket description was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_description }
      else
        format.html { render :new }
        format.json { render json: @ticket_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_descriptions/1
  # PATCH/PUT /ticket_descriptions/1.json
  def update
    respond_to do |format|
      if @ticket_description.update(ticket_description_params)
        format.html { redirect_to @ticket_description, notice: 'Ticket description was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_description }
      else
        format.html { render :edit }
        format.json { render json: @ticket_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_descriptions/1
  # DELETE /ticket_descriptions/1.json
  def destroy
    @ticket_description.destroy
    respond_to do |format|
      format.html { redirect_to ticket_descriptions_url, notice: 'Ticket description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_description
      @ticket_description = TicketDescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_description_params
      params.require(:ticket_description).permit(:title)
    end
end

app/helpers/ticket_descriptions_helper.rb
module TicketDescriptionsHelper
end

app/views/ticket_descriptions/_form.html.erb
<%= form_with(model: ticket_description, local: true) do |form| %>
  <% if ticket_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket_description.errors.count, "error") %> prohibited this ticket_description from being saved:</h2>

      <ul>
      <% ticket_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :ticket_description_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ticket_descriptions/edit.html.erb
<h1>Editing Ticket Description</h1>

<%= render 'form', ticket_description: @ticket_description %>

<%= link_to 'Show', @ticket_description %> |
<%= link_to 'Back', ticket_descriptions_path %>

app/views/ticket_descriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ticket Descriptions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_descriptions.each do |ticket_description| %>
      <tr>
        <td><%= ticket_description.title %></td>
        <td><%= link_to 'Show', ticket_description %></td>
        <td><%= link_to 'Edit', edit_ticket_description_path(ticket_description) %></td>
        <td><%= link_to 'Destroy', ticket_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket Description', new_ticket_description_path %>

app/views/ticket_descriptions/new.html.erb
<h1>New Ticket Description</h1>

<%= render 'form', ticket_description: @ticket_description %>

<%= link_to 'Back', ticket_descriptions_path %>

app/views/ticket_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket_description.title %>
</p>

<%= link_to 'Edit', edit_ticket_description_path(@ticket_description) %> |
<%= link_to 'Back', ticket_descriptions_path %>