config/routes.rb
Rails.application.routes.draw do

  get "profile", to: "pages#settings"
  get "stat", to: 'pages#statistics'
  get "settings/reload", to: "pages#reload"
  get "get_sites", to: "pages#get_sites"
  get "get_deadline", to: "pages#get_deadline"
  #get "settings/new_db", to: "pages#new_db"
  resources :cmd, only: [:new, :create]

  resources :tickets, param: :number do
    member do
      post 'create_message'
    end
  end
  resources :role_permissions
  get 'reports/create'
  resources :reports,  only: [:new]
  resources :roles, controller: :p_roles

  get 'photo_reports/create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :jobs
  resources :prices
  resources :accounts do
    resource :password, only: [:new, :update] do
      member do
        get :switch
      end
    end
    resource :roles, controller: 'ars' , only: [:create, :destroy]
  end
  resources :brigades
  resources :ticket_types
  resources :statuses
  resources :photos, controller: 'images'
  resources :documents
  resources :ticket_descriptions
  resources :sites do
    resources :photos
  end

  root to: 'tickets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  belongs_to :role
  belongs_to :status, optional: true

  validates :role_id, presence: true
end

app/controllers/role_permissions_controller.rb
class RolePermissionsController < ApplicationController
  before_action :set_role_permission, only: [:show, :edit, :update, :destroy]
  before_action :get_permissions

  # GET /role_permissions
  # GET /role_permissions.json
  def index
    @role_permissions = RolePermission.all
  end

  # GET /role_permissions/1
  # GET /role_permissions/1.json
  def show
  end

  # GET /role_permissions/new
  def new
    @role_permission = RolePermission.new
    @statuses = Status.all
    @roles = Role.all
  end

  # GET /role_permissions/1/edit
  def edit
    @statuses = Status.all
    @roles = Role.all
    @permissions = Permission.new( @role_permission.permissions )
  end

  # POST /role_permissions
  # POST /role_permissions.json
  def create
    @role_permission = RolePermission.new(role_permission_params)
    @statuses = Status.all
    @roles = Role.all
    @permission = Permission.new(role_permission_prms)
    @role_permission.permissions = @permission.to_string

    begin
      respond_to do |format|
        if @role_permission.save
          format.html { redirect_to @role_permission, notice: 'Role permission was successfully created.' }
          format.json { render :show, status: :created, location: @role_permission }
        else
          format.html { render :new }
          format.json { render json: @role_permission.errors, status: :unprocessable_entity }
        end
      end
    rescue => error
      puts error.inspect
      redirect_to role_permissions_path
    end
  end

  # PATCH/PUT /role_permissions/1
  # PATCH/PUT /role_permissions/1.json
  def update
    @permission = Permission.new( params[:prms] )
    p role_permission_params
    #if @permission.size == 0
    #  rp_params = role_permission_params
    #else
      rp_params = role_permission_params.to_h.merge!( permissions: @permission.to_string )
    #end
    respond_to do |format|
      if @role_permission.update( rp_params )
        format.html { redirect_to role_permissions_path, notice: 'Role permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @role_permission }
      else
        format.html { render :edit }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_permissions/1
  # DELETE /role_permissions/1.json
  def destroy
    @role_permission.destroy
    respond_to do |format|
      format.html { redirect_to role_permissions_url, notice: 'Role permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_role_permission
    @role_permission = RolePermission.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_permission_params
    params.require(:role_permission).permit(:role_id, :status_id, :permissions, :statuses)
  end

  def role_permission_prms
    prms = params.fetch(:prms, {}).permit!
  end

  def get_permissions
    raise ActionController::RoutingError.new('Not Found') unless current_user.can?('edit_permissions')
  end
end

app/helpers/role_permissions_helper.rb
module RolePermissionsHelper
end

app/views/role_permissions/_form.html.erb
<%= form_with(model: role_permission, local: true) do |form| %>
<% if role_permission.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(role_permission.errors.count, "error") %> prohibited this role_permission from being saved:</h2>

  <ul>
    <% role_permission.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="actions">
    <%= form.submit "Сохранить" %>
  </div>
</div>
<div class="row gutters">
  <div class="col col-2">
    <div class="field">
      <strong>Роль</strong>
      <%= form.collection_select :role_id, @roles, :id, :title, {:include_blank => 'нет'}, {:disabled => 'disabled'} %>
    </div>

    <div class="field">
      <strong>Статус</strong>
      <%= form.collection_select :status_id, @statuses, :id, :title, {:include_blank => 'нет'}, {:disabled => 'disabled'} %>
    </div>
  </div>
  <div class="col col-9">

    <div class="row vertical-gut" id="permissions_list">
      <div class="col col-12">
        <strong>Разрешения</strong>
      </div>
      <div class="col col-12 vertical-gut">
        <%= form.text_field :permissions, id: :role_permission_permissions %>
      </div>
      <% unless @permissions.size == 0 %>
      <% @permissions.list.each do |l| %>
      <div class="col col-2" name="<%= l %>">
        <%= check_box :prms.to_s, "#{ l }", { checked: ( @permissions.prms(l) == '1' )} %> - <%= l %> (<%= link_to "Удалить", "#", class: "del_perm" %>)
      </div>
      <% end %>
      <% end %>
    </div>
    <div class="row vertical-gut">
      <div class="col col-3 append" id="new_permission">
        <%= text_field_tag :new_permission, '',  id: 'new_permission_name' %>
        <%= link_to "Создать", "#", class: "button new_permission" %>
      </div>
    </div><br>
    <div class="row">
      <div class="col col-12">
        <strong>Доступные статусы заявок</strong>
      </div>
      <div class="col col-12 prepend">
        <span>Статусы</span>
        <%= form.text_field :statuses %>
      </div>
    </div>

  </div>
</div>

<% end %>

app/views/role_permissions/edit.html.erb
<h1>Editing Role Permission</h1>

<%= render 'form', role_permission: @role_permission %>

<%= link_to 'Show', @role_permission %> |
<%= link_to 'Back', role_permissions_path %>

app/views/role_permissions/index.html.erb
<h1>Role Permissions</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Status</th>
      <th>Permissions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @role_permissions.each do |role_permission| %>
      <tr>
        <td><%= role_permission.role.title unless role_permission.role.nil? %></td>
        <td><%= role_permission.status.title unless role_permission.status.nil?  %></td>
        <td><%= role_permission.permissions %></td>
        <td><%= link_to 'Show', role_permission %></td>
        <td><%= link_to 'Edit', edit_role_permission_path(role_permission) %></td>
        <td><%= link_to 'Destroy', role_permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role Permission', new_role_permission_path %>

app/views/role_permissions/new.html.erb
<h1>New Role Permission</h1>

<%= render 'form', role_permission: @role_permission %>

<%= link_to 'Back', role_permissions_path %>

app/views/role_permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @role_permission.role_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @role_permission.status_id %>
</p>

<p>
  <strong>Permissions:</strong>
  <%= @role_permission.permissions %>
</p>

<%= link_to 'Edit', edit_role_permission_path(@role_permission) %> |
<%= link_to 'Back', role_permissions_path %>