config/routes.rb
Rails.application.routes.draw do

  get "profile", to: "pages#settings"
  get "stat", to: 'pages#statistics'
  get "settings/reload", to: "pages#reload"
  get "get_sites", to: "pages#get_sites"
  get "get_deadline", to: "pages#get_deadline"
  #get "settings/new_db", to: "pages#new_db"
  resources :cmd, only: [:new, :create]

  resources :tickets, param: :number do
    member do
      post 'create_message'
    end
  end
  resources :role_permissions
  get 'reports/create'
  resources :reports,  only: [:new]
  resources :roles, controller: :p_roles

  get 'photo_reports/create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :jobs
  resources :prices
  resources :accounts do
    resource :password, only: [:new, :update] do
      member do
        get :switch
      end
    end
    resource :roles, controller: 'ars' , only: [:create, :destroy]
  end
  resources :brigades
  resources :ticket_types
  resources :statuses
  resources :photos, controller: 'images'
  resources :documents
  resources :ticket_descriptions
  resources :sites do
    resources :photos
  end

  root to: 'tickets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/account.rb
require 'digest'

class Account < ApplicationRecord
  has_one :password
  has_many :tickets, :foreign_key => 'author_id'
  has_and_belongs_to_many :roles, :through => :accounts_roles

  attr_accessor :prms, :status_id

  before_create do |ac|
    if Account.all.size == 0
      ac.is_root = true
    end
    ac.email.downcase!
  end
  after_create do |ac|
    p = Password.create(secret: nil, active: false, last_changed: nil, account_id: ac.id)
  end

  def statuses(s)
    result = []
    self.roles.each do |role|
      role_permission = role.role_permissions.where(status_id: s).first
      str = role_permission.statuses unless role_permission.nil?
      result << eval(str) unless str == "" or str.nil?
    end
    result.flatten.uniq
  end

  def can?(key)
    can_st?(key, nil)
  end

  def can_st?(key, s)
    return true if self.is_root == true

    #ar = (!@param_str.nil?) ? @param_str : prms(s)
    ar = prms(s)
    #p ar
    return false if ar == [] or ar.nil?

    result = ar.key?(key) ? ar[key] : false
    result == '1' ? true : false
  end

  private

  def prms(s)
    result = []
    return result if self.roles.size == 0

    statuses = []
    statuses << nil
    statuses << s unless s.nil?
    self.roles.each do |role|
      statuses.each do |stat|
        rprms = role.role_permissions.where(status_id: stat).first
        p_str = rprms.permissions unless rprms.nil?
        #p "PERMISSIONS - #{ p_str }"
        result << eval(p_str) unless p_str == "" or p_str.nil?
      end
    end
    p "arrays - #{result.size}"
    @param_str = conjunc_array(result)
    #p "PARAM STRING - #{@param_str.size}"
    @param_str
  end

  def conjunc_couple( hash1, hash2 )
    result = hash1
    result.each do |k, v|
      result[k] = (hash2.key?(k) and hash2[k] == '1') ? '1' : v
      p "#{k}: h1 - #{v} :: h2 - #{ hash2[k] }"
      p "        result: #{ result[k] }"
      hash2.delete(k)
    end
    result.update(hash2) if hash2.size > 0
    result
  end

  def conjunc_array(arr)
    result = arr.shift
    arr.each do |a|
      result = conjunc_couple(result, a)
    end
    #p "DATA - #{ result }"
    result
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :get_permissions

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @roles_aviable = Role.all - @account.roles
    @role = Role.new
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :name_long, :is_service, :email, :is_client)
  end

  def get_permissions
    raise ActionController::RoutingError.new('Not Found') unless current_user.can?('edit_accounts')
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :account_name %>
  </div>

  <div class="field">
    <%= form.label :name_long %>
    <%= form.text_field :name_long, id: :account_name_long %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :account_email %>
  </div>

  <div class="field">
    <%= form.label :is_client %>
    <%= form.check_box :is_client, id: :account_is_client %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Name long</th>
      <th>Is client</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
    <tr class="<%= "account_on" if account.password.active %>">
      <td><%= account.email %></td>
      <td><%= account.name %></td>
      <td><%= account.name_long %></td>
      <td><%= account.is_client | false %></td>
      <td>
        <% if account.password.secret.nil? %>
        <%= link_to "Установить пароль", new_account_password_path(account), class: "btn btn-primary" %>
        <% else %>
        <%= link_to "Изменить пароль", new_account_password_path(account), class: "btn btn-primary" %>
        <% end %>
      </td>
      <td>
        <% unless account.password.active %>
        <%= link_to "Активировать", switch_account_password_path(account), class: "btn btn-primary" %>
        <% else %>
        <%= link_to "Деактивировать", switch_account_password_path(account), class: "btn btn-primary" %>
        <% end %>
      </td>
      <td><%= link_to 'Show', account %></td>
      <td><%= link_to 'Edit', edit_account_path(account) %></td>
      <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<div class="site_form">
  <h3>  <%= link_to 'Пользователи', accounts_path %></h3>
  <p>
    Пользователь: <strong><%= @account.name_long or @account.name %></strong>
  </p>
  <p>
    E-mail: <strong><%= @account.email %></strong>
  </p>
  <div class="row">
    <div class="col col-4">

      <div class="row">
        <strong>Активные роли:</strong>
      </div>
      <% if @account.roles.size == 0 %>
      <div class="row">
        Нет ролей
      </div>
      <% end %>

      <%= form_for [@account, @role] do |f| %>
      <% @account.roles.each do |r| %>
      <div class="row gutters">
        <div class="col col-7">
          <p><%= text_field_tag :r, r.title, disabled: 'disabled' %></p>
        </div>
        <div class="col col-5">
          <%= link_to 'Удалить', account_roles_path(@account.id, r.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
        </div>
      </div>
      <% end %>
      <% unless @roles_aviable.size == 0 %>
      <div class="row">
        <strong>Доступные:</strong>
      </div>
      <div class="row gutters">
        <div class="col col-7">
          <%= f.collection_select :id, @roles_aviable, :id, :title %>
        </div>
        <div class="col col-5">
          <%= f.submit "Добавить", class: 'button' %>
        </div>
      </div>
      <% end %>
      <% end %>

    </div>
  </div>

</div>